# This file was generated by GoReleaser. DO NOT EDIT.
class Ohctl < Formula
  desc ""
  homepage "https://github.com/choppedpork/ohctl"
  url "https://github.com/choppedpork/ohctl/releases/download/v0.1.0/ohctl_0.1.0_Darwin_x86_64.tar.gz"
  version "0.1.0"
  sha256 "bc53465575f4a4fd4d9a05cb1b38a28673be856343fcea16ec520c780a97da31"

  def install
    bin.install "ohctl"
  end
end
